// Generated by CoffeeScript 1.12.6
(function() {
  var Beatrix, Manager, Promise, Sift, _, uuid;

  Beatrix = require('beatrix');

  Sift = require('sift');

  _ = require('lodash');

  uuid = require('uuid');

  Promise = require('bluebird');

  Manager = (function() {
    function Manager() {}

    Manager.prototype.name = null;

    Manager.prototype.ready = null;

    Manager.prototype.connection = null;

    Manager.prototype.connect = function(options, cb) {
      this.name = options.name;
      return this.ready = new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.connection = Beatrix({
            connection: {
              uri: options.uri
            },
            exchange: _.defaults({}, options.exchange, {
              name: 'events',
              autoDelete: false,
              durable: true,
              type: 'topic'
            }, {
              responseQueue: false
            })
          }, function(err, res) {
            if (err) {
              return reject(err);
            } else {
              return resolve(res);
            }
          });
        };
      })(this));
    };

    Manager.prototype.filter = function(filter, message) {
      if ('function' === typeof filter) {
        return filter(message);
      }
      if ('object' === typeof filter) {
        return Sift(filter)(message);
      }
      return true;
    };

    Manager.prototype.on = function(event, options, method) {
      return this.ready.then((function(_this) {
        return function() {
          options = _.defaults({}, options, {
            name: _this.name + '.' + event,
            type: _this.name + '.' + event,
            routingKey: event,
            autoDelete: options.persistent === false,
            durable: options.persistent !== false,
            context: _this
          });
          options.process = function(message, cb) {
            var base, base1;
            if ((base = message.body).type == null) {
              base.type = message.fields.routingKey;
            }
            if ((base1 = message.body).typeArray == null) {
              base1.typeArray = message.fields.routingKey.split('.');
            }
            if (!_this.filter(options.filter, message.body)) {
              return cb(null, 'Filtered');
            }
            return method(message.body).then(function(result) {
              return cb(null, result);
            })["catch"](function(err) {
              return cb(err);
            });
          };
          return new Promise(function(resolve, reject) {
            return _this.connection.createQueue(event, options, function(err, result) {
              if (err) {
                return reject(err);
              } else {
                return resolve(result);
              }
            });
          });
        };
      })(this));
    };

    Manager.prototype.emit = function(event, body, options) {
      options = _.defaults({}, options, {
        routingKey: event
      });
      return this.ready.then((function(_this) {
        return function() {
          return new Promise(function(resolve, reject) {
            return _this.connection.publish(event, body, options, function(err, result) {
              if (err) {
                return reject(err);
              } else {
                return resolve(result);
              }
            });
          });
        };
      })(this));
    };

    return Manager;

  })();

  module.exports = new Manager();

}).call(this);

//# sourceMappingURL=index.js.map
